//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Builder
{
    protected Product product;

    public virtual Product Product
    {
        get { return product; }
    }

    public abstract void buildPart1();

    public abstract void buildPart2();

    public abstract void buildPart3();

    public virtual void constructProduct()
    {
        this.product = new Product();
    }

}

