//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConcreteBuilder1 : Builder
{
	public override void buildPart1()
	{
        this.product.Part1 = "Part1 Done";		
	}

	public override void buildPart2()
	{
        this.product.Part2 = "Part2 Done";        
	}

	public override void buildPart3()
	{
        this.product.Part3 = "Part3 Done";        
	}
}

