//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Director
{
	private Builder builder;

	public virtual Builder Builder
	{
        get { return builder; }
        set { builder = value; }
    }

	public virtual void createProduct()
	{
        builder.constructProduct();
        builder.buildPart1();
        builder.buildPart2();
        builder.buildPart3();		
	}

	public virtual Product getProduct()
	{
        return builder.Product;		
	}

}

