//------------------------------------------------------------------------------
// <auto-generated>
//     此程式碼是由工具產生
//     如果重新產生程式碼，將會遺失此檔案的變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product
{
	private string part1;

	private string part2;

	private string part3;

	public virtual string Part1
	{
		get {return part1; }
        set {part1=value; }
	}

	public virtual string Part2
	{
        get { return part2; }
        set { part2 = value; }
    }

	public virtual string Part3
	{
        get { return part3; }
        set { part3 = value; }
    }

}

